config/routes.rb
Rails.application.routes.draw do
  resources :elements, only: [:index, :show]
  resources :products, only: [:index, :show]

  root to: 'elements#index'
end

app/helpers/product_elements_helper.rb
module ProductElementsHelper
end

app/views/product_elements/_form.html.erb
<%= form_with model: Element.new, url: product_elements_path, method: :get, id: 'search-form' do |f| %>
  <div class="form" data-search="0">
    <div class="form-row align-items-center">
      <div class="input-group align-items-center rounded-border bg-white">
        <div class="input-group-prepend">
          <div class="input-group-text bg-transparent rounded-left-border border-0">
            <span><%= (fa_icon "search") %></span>
          </div>
        </div>
        <%= select_tag "product_element[search]", options_for_select(Product.search), {class: "form-control border-0 search-select"} %>
        <div class="input-group-append">
          <div class="input-group-text bg-transparent border-top-0 border-right-0 border-bottom-0">
            <span> </span>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/product_elements/index.js.erb
var form = $("#search-form");
var idx = $(form).find(".form").attr("data-search");
$(form).html("<%= j render 'product_elements/form' %>");
$(form).find(".form").attr("data-search", idx);
$(form).find('select option').eq(idx).attr('selected', true);
$("#tab-index").html("<%= j render 'product_elements/tabs', products: @products %>");